### PR TITLE
Major update to CRCL

### PR DESCRIPTION
**Pull request by frederickproctor**
The CRCL team (NIST and Georgia Tech) have completed a major restructuring of the CRCL code. The XML schemas have been changed a small amount, but the directory structure has been changed a lot to more cleanly separate the common material from language-specific tools. The new code has been tested, and the team thinks it's time to merge it into the ros-industrial/crcl repo.

### CODE REVIEW

**Comment by wshackle** [comment]
Testing section of top-level README.md refers to the frederickproctor fork of CRCL. 

git clone git@github.com:frederickproctor/crcl

Normally README.md files don't cover the clone instructions because a person with the README should have already cloned the repo already and it would be really strange to merge this which means after checking out the main repo you would be told to check out the frederickproctor fork.

Test instructions at the top-level seem to only be for the C++ version.

**Comment by frederickproctor** [comment]
Good point; I changed the top-level README.md file so that it describes the language tools, and takes out the build instructions.

**Comment by gavanderhoorn** [comment]
A bit late perhaps, but having build instructions in a readme is actually pretty common. I wouldn't point end-users to private forks though.

As to having `git clone ..` instructions in your readme: for Github repositories the top-level `README.md` file (and variants) also function as landing pages for your repository. Depending on the audience you are catering to, including some brief instructions on how to quickly get going seems not such a bad idea.

**Comment by frederickproctor** [comment]
I'd like to merge the pull request - I expect that we'll be updating our language tools as the next step, and this will be helped if we get the latest schemas merged in to the master branch. Any dissenters?

**Comment by gavanderhoorn** [comment]
Suggestion: squash some of the commits before merging (*Update README.md* fi)?

**Comment by shaun-edwards** [comment]
@frederickproctor, thanks for this.  @gavanderhoorn's comments are always welcome and constructive.  If @wshackle agrees with the PR, then please don't feel like you have to wait for anyone else.  The PR "rules" are just that someone else agrees to the change.  Since @wshackle is working on the project, I can't think of anyone better to review.

**Comment by frederickproctor** [comment]
I'll merge it now. There was one commit I made to my fork that split out a library in a CMakeLists.txt file. It should go in without a hitch.

**Pull request merged**
